version: 2
updates:
  # Check updates to action versions in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions monthly, on the first day of the month
      interval: "monthly"
