# permissions for end users to edit ccruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccruntime-editor-role
rules:
- apiGroups:
  - confidentialcontainers.org
  - peerpodconfiguration.confidentialcontainers.org
  resources:
  - ccruntimes
  - peerpodconfigs
  - peerpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  - peerpodconfiguration.confidentialcontainers.org
  resources:
  - ccruntimes/status
  - peerpodconfigs/status
  - peerpods/status
  verbs:
  - get
