apiVersion: confidentialcontainers.org/v1beta1
kind: CcRuntime
metadata:
  name: ccruntime-sample
  namespace: confidential-containers-system
spec:
  ccNodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ''
  config:
    cleanupCmd:
      - /opt/kata-artifacts/scripts/kata-deploy.sh
      - reset
    environmentVariables:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: CONFIGURE_CC
        value: 'yes'
    installCmd:
      - /opt/kata-artifacts/scripts/kata-deploy.sh
      - install
    installDoneLabel:
      katacontainers.io/kata-runtime: 'true'
    installType: bundle
    installerVolumeMounts:
      - mountPath: /etc/containerd/
        name: containerd-conf
      - mountPath: /opt/confidential-containers/
        name: kata-artifacts
      - mountPath: /var/run/dbus
        name: dbus
      - mountPath: /run/systemd
        name: systemd
      - mountPath: /usr/local/bin/
        name: local-bin
    installerVolumes:
      - hostPath:
          path: /etc/containerd/
          type: ''
        name: containerd-conf
      - hostPath:
          path: /opt/confidential-containers/
          type: DirectoryOrCreate
        name: kata-artifacts
      - hostPath:
          path: /var/run/dbus
          type: ''
        name: dbus
      - hostPath:
          path: /run/systemd
          type: ''
        name: systemd
      - hostPath:
          path: /usr/local/bin/
          type: ''
        name: local-bin
    payloadImage: >-
      quay.io/confidential-containers/runtime-payload:kata-containers-129e43d1ea5cca528b7b97234b7561219208a244-x86_64
    postUninstall:
      image: >-
        quay.io/confidential-containers/container-engine-for-cc-payload:1def978fdf6b0cb2383d43970c3dc484df3cad54
      volumeMounts:
        - mountPath: /opt/confidential-containers/
          name: confidential-containers-artifacts
        - mountPath: /etc/systemd/system/
          name: etc-systemd-system
        - mountPath: /var/run/dbus
          name: dbus
        - mountPath: /run/systemd
          name: systemd
      volumes:
        - hostPath:
            path: /opt/confidential-containers/
            type: DirectoryOrCreate
          name: confidential-containers-artifacts
        - hostPath:
            path: /etc/systemd/system/
            type: ''
          name: etc-systemd-system
        - hostPath:
            path: /var/run/dbus
            type: ''
          name: dbus
        - hostPath:
            path: /run/systemd
            type: ''
          name: systemd
    preInstall:
      image: >-
        quay.io/confidential-containers/container-engine-for-cc-payload:1def978fdf6b0cb2383d43970c3dc484df3cad54
      volumeMounts:
        - mountPath: /opt/confidential-containers/
          name: confidential-containers-artifacts
        - mountPath: /etc/systemd/system/
          name: etc-systemd-system
        - mountPath: /var/run/dbus
          name: dbus
        - mountPath: /run/systemd
          name: systemd
      volumes:
        - hostPath:
            path: /opt/confidential-containers/
            type: DirectoryOrCreate
          name: confidential-containers-artifacts
        - hostPath:
            path: /etc/systemd/system/
            type: ''
          name: etc-systemd-system
        - hostPath:
            path: /var/run/dbus
            type: ''
          name: dbus
        - hostPath:
            path: /run/systemd
            type: ''
          name: systemd
    runtimeClassNames:
      - kata
      - kata-clh
      - kata-clh-tdx
      - kata-qemu
      - kata-qemu-tdx
      - kata-qemu-sev
    uninstallCmd:
      - /opt/kata-artifacts/scripts/kata-deploy.sh
      - cleanup
    uninstallDoneLabel:
      katacontainers.io/kata-runtime: cleanup
  runtimeName: kata
