resources:
- ../base

nameSuffix: -sgx-mode-sim

images:
- name: quay.io/confidential-containers/runtime-payload
  newTag: enclave-cc-SIM-sample-kbc-v0.8.0
- name: quay.io/confidential-containers/reqs-payload
  newTag: c31205eb31d8a4623ffc0c9fa316e3c91e337023
