name: ccruntime e2e test nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  e2e-nightly:
    uses: ./.github/workflows/ccruntime_e2e.yaml

  e2e-ibm-se-nightly:
    runs-on: s390x
    strategy:
      fail-fast: false
      matrix:
        test_title:
          - cc-operator-e2e-tests
    steps:
    - name: Fetch a test result for {{ matrix.test_title }}
      run: |
        file_name="${TEST_TITLE}-$(date +%Y-%m-%d).log"
        /home/${USER}/script/handle_test_log.sh download $file_name
      env:
        TEST_TITLE: ${{ matrix.test_title }}
